In [7]:
import pandas as pd

# read in datasets 
mcsilver_data = pd.read_excel("./in/McSilver_NYCProgramExport_10032024.xlsx")
omh_data = pd.read_excel("./in/OMH_ProgramDirectory_11082024.xlsx")
oasas_treatment_data = pd.read_csv("./in/OASAS_TreatmentPrograms_11082024.csv")
oasas_prevention_data = pd.read_csv("./in/OASAS_PreventionPrograms_11082024.csv")

# 1. Viewing and exploring data

In [8]:
mcsilver_data.head()

,ACG id,internal id,type,agency acg id,agency,name,city,state,zip,county,...,category,sub category,populations served,program project type,nyc ros,license designation,date created,closed,closed date,draft
0,6,1700005,Outpatient Clinic,4.0,Counseling Service of E.D.N.Y.,Outpatient Service (822)- Remsen Street,Brooklyn,NY,11201,Kings,...,Oasas,Outpatient Services,"Under 18- OASAS,18-21- OASAS,12-21- OASAS",MCTAC,NYC,OASAS,2017-08-21,NaN,NaN,NaN
1,7,1700006,Outpatient Clinic,4.0,Counseling Service of E.D.N.Y.,Outpatient Services (822-4)- Joralemon Street,Brooklyn,NY,11201,Kings,...,Oasas,Outpatient Services,18-21- OASAS,MCTAC,NYC,OASAS,2017-08-21,NaN,NaN,NaN
2,8,1700007,Outpatient Clinic,4.0,Counseling Service of E.D.N.Y.,Outpatient Services (822-4)- Jamaica Avenue,Jamaica,NY,11432,Queens,...,Oasas,Outpatient Services,"Under 18- OASAS,18-21- OASAS,12-21- OASAS",MCTAC,NYC,OASAS,2017-08-21,NaN,NaN,NaN
3,9,1700008,Outpatient Clinic,5.0,Dynamic Youth Community,Outpatient Service (822)- Coney Island Avenue,Brooklyn,NY,11230,Kings,...,Oasas,Outpatient Services,18-21- OASAS,MCTAC,NYC,OASAS,2017-08-21,NaN,NaN,NaN
4,12,1700011,Outpatient Clinic,6.0,Elmcor Youth and Adult Activities,Outpatient Services (822-4)- Northern Boulevard,Corona,NY,11368,Queens,...,Oasas,Outpatient Services,"Under 18- OASAS,18-21- OASAS,12-21- OASAS",MCTAC,NYC,OASAS,2017-08-21,NaN,NaN,NaN

In [9]:
# we want to merge on omhProgramCode, omhFacilityCode, and OMH/OASAS Agency Code
mcsilver_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2156 entries, 0 to 2155
Data columns (total 41 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   ACG id                               2156 non-null   int64
 1   internal id                          2156 non-null   int64
 2   type                                 2154 non-null   object
 3   agency acg id                        2154 non-null   float64
 4   agency                               2154 non-null   object
 5   name                                 2156 non-null   object
 6   city                                 1510 non-null   object
 7   state                                2156 non-null   object
 8   zip                                  1510 non-null   object
 9   county                               1505 non-null   object
 10  region omh                           778 non-null    object
 11  region oasas                         273 non-null    object
 12  region ocfs                          21 non-null     object
 13  region rpc                           1506 non-null   object
 14  oasasProgramCode                     322 non-null    object
 15  omhProgramCode                       1291 non-null   object
 16  omhFacilityCode                      1125 non-null   object
 17  childrensLeadHHMMISCode              12 non-null     float64
 18  childrensCMAMMISCode                 224 non-null    object
 19  adultHHCMAProgramCode                12 non-null     object
 20  adultHCBSCode                        51 non-null     object
 21  OMH/OASAS Agency Code                2130 non-null   object
 22  OCFS Agency Code                     333 non-null    object
 23  OPWDD Agency Code                    541 non-null    float64
 24  OPWDD Program Code                   1 non-null      object
 25  HCBS Childrens Aligned Agency Code   709 non-null    object
 26  CFTSS Agency Code                    790 non-null    object
 27  HCBS Childrens Aligned Program Code  79 non-null     object
 28  CFTSS Program Code                   134 non-null    object
 29  puCode                               2156 non-null   object
 30  siteCode                             1087 non-null   object
 31  category                             1458 non-null   object
 32  sub category                         1458 non-null   object
 33  populations served                   2019 non-null   object
 34  program project type                 2155 non-null   object
 35  nyc ros                              1929 non-null   object
 36  license designation                  2156 non-null   object
 37  date created                         1496 non-null   datetime64[ns]
 38  closed                               0 non-null      float64
 39  closed date                          0 non-null      float64
 40  draft                                2 non-null      object
dtypes: datetime64[ns](1), float64(5), int64(2), object(33)
memory usage: 690.7+ KB

In [10]:
omh_data.head()

,Sponsor Name,Agency Name,Program Name,Population Served,Agency Phone,Program Phone,Program Address 1,Program Address 2,Program City,Program State,...,Operating Certificate Duration,Program County,Program Region,Program Type,Program Category,Program Subcategory,Sponsor Code,Agency Code,Facility Code,Program Code
0,1003 Walnut Street/dba Sol Stone Center,1003 Walnut Street/dba Sol Stone Center,Sol Stone Center,Adults,(877)Â 765-7866,(877)Â 765-7866,1003 Walnut Street,NaN,Elmira,NY,...,36/36,Chemung,Western New York,Partial Hospitalization,Outpatient,Partial Hospitalization,810099,44810,7810,1
1,163rd Street Improvement Council,163rd Street Improvement Council,Flossie Wilson Residence,Adults,(347)Â 978-1139,(347)Â 978-1139,Agency Phone:Â (347)Â 978-1139,NaN,NaN,NY,...,36/36,Bronx,New York City,SRO Community Residence,Residential,Treatment Program,724099,30510,9233,1
2,"ACMH, Inc.","ACMH, Inc.",74th Avenue-A,Adults,(212)Â 274-8558,(212)Â 274-8558,Agency Phone:Â (212)Â 274-8558,NaN,NaN,NY,...,36/36,Queens,New York City,SRO Community Residence,Residential,Treatment Program,27099,18780,7062,6
3,"ACMH, Inc.","ACMH, Inc.",ACMH - HH CM,Adults,(212)Â 274-8558,(212)Â 274-8558,545 Eighth Avenue,Room 910,New York,NY,...,NaN,New York,New York City,Health Home Care Management,Support,Care Coordination,27099,18780,7062,10
4,"ACMH, Inc.","ACMH, Inc.",ACMH - HH NonMed CM,Adults,(212)Â 274-8558,(212)Â 274-8558,545 Eighth Avenue,Room 610,New York,NY,...,NaN,New York,New York City,Health Home Non-Medicaid Care Management,Support,Care Coordination,27099,18780,7062,11

In [11]:
omh_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6322 entries, 0 to 6321
Data columns (total 23 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Sponsor Name                     6322 non-null   object
 1   Agency Name                      6322 non-null   object
 2   Program Name                     6322 non-null   object
 3   Population Served                5757 non-null   object
 4   Agency Phone                     6322 non-null   object
 5   Program Phone                    6322 non-null   object
 6   Program Address 1                6322 non-null   object
 7   Program Address 2                1083 non-null   object
 8   Program City                     4619 non-null   object
 9   Program State                    6322 non-null   object
 10  Program Zip                      4619 non-null   object
 11  Operating Certificate Required?  6322 non-null   object
 12  Program Tier                     7 non-null      float64
 13  Operating Certificate Duration   1489 non-null   object
 14  Program County                   6322 non-null   object
 15  Program Region                   6322 non-null   object
 16  Program Type                     6322 non-null   object
 17  Program Category                 6322 non-null   object
 18  Program Subcategory              6322 non-null   object
 19  Sponsor Code                     6322 non-null   int64
 20  Agency Code                      6322 non-null   int64
 21  Facility Code                    6322 non-null   int64
 22  Program Code                     6322 non-null   int64
dtypes: float64(1), int64(4), object(18)
memory usage: 1.1+ MB

In [12]:
oasas_treatment_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311 entries, 0 to 310
Data columns (total 34 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   PROVIDER_NAME                     311 non-null    object
 1   PROVIDER_NUMBER                   311 non-null    int64
 2   PROVIDER_STREET                   311 non-null    object
 3   PROVIDER_CITY                     311 non-null    object
 4   PROVIDER_COUNTY                   311 non-null    object
 5   PROVIDER_STATE                    311 non-null    object
 6   PROVIDER_ZIP_CODE                 311 non-null    int64
 7   PROVIDER_ZIP_CODE_PLUS_4          165 non-null    float64
 8   PROGRAM_NAME                      311 non-null    object
 9   PROGRAM_NUMBER                    311 non-null    int64
 10  PROGRAM_COUNTY                    311 non-null    object
 11  PROGRAM_STREET_ADDRESS            311 non-null    object
 12  PROGRAM_CITY                      311 non-null    object
 13  PROGRAM_STATE                     311 non-null    object
 14  PROGRAM_ZIP_CODE                  311 non-null    int64
 15  PROGRAM_ZIP_CODE_PLUS_4           113 non-null    float64
 16  PROGRAM_DIRECTOR                  311 non-null    object
 17  PROGRAM_DIRECTOR_EMAIL            311 non-null    object
 18  PROGRAM_DIRECTOR_TELEPHONE        311 non-null    int64
 19  PROGRAM_DIRECTOR_PHONE_EXTENSION  83 non-null     float64
 20  PROGRAM_TYPE                      311 non-null    object
 21  SERVICE_TYPE                      311 non-null    object
 22  ADMISSION_PHONE                   183 non-null    float64
 23  ADMISSION_PHONE_EXT               57 non-null     float64
 24  TELEHEALTH_SERVICES               251 non-null    object
 25  ADOLESCENT_DESIGNATION            4 non-null      object
 26  PROBLEM_GAMBLING                  8 non-null      object
 27  INTEGRATED_LICENSE_SERVICE        29 non-null     object
 28  PARENTS_WITH_CHILDREN             7 non-null      object
 29  LGBTQ_ENDORSEMNT                  6 non-null      object
 30  ADDITIONAL_LOCATION_STREET        33 non-null     object
 31  ADDITIONAL_LOCATION_CITY          33 non-null     object
 32  ADDITIONAL_LOCATION_ZIP           33 non-null     float64
 33  ADDITIONAL_LOCATION_COUNTYNAME    33 non-null     object
dtypes: float64(6), int64(5), object(23)
memory usage: 82.7+ KB

In [13]:
oasas_prevention_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 22 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   PROVIDER_NAME                     63 non-null     object
 1   PROVIDER_NUMBER                   63 non-null     int64
 2   PROVIDER_STREET                   63 non-null     object
 3   PROVIDER_CITY                     63 non-null     object
 4   PROVIDER_COUNTY                   63 non-null     object
 5   PROVIDER_STATE                    63 non-null     object
 6   PROVIDER_ZIP_CODE                 63 non-null     int64
 7   PROVIDER_ZIP_CODE_PLUS_4          11 non-null     float64
 8   PROGRAM_NAME                      63 non-null     object
 9   PROGRAM_NUMBER                    63 non-null     int64
 10  PROGRAM_COUNTY                    63 non-null     object
 11  PROGRAM_STREET_ADDRESS            63 non-null     object
 12  PROGRAM_CITY                      63 non-null     object
 13  PROGRAM_STATE                     63 non-null     object
 14  PROGRAM_ZIP_CODE                  63 non-null     int64
 15  PROGRAM_ZIP_CODE_PLUS_4           24 non-null     float64
 16  PROGRAM_DIRECTOR                  63 non-null     object
 17  PROGRAM_DIRECTOR_EMAIL            63 non-null     object
 18  PROGRAM_DIRECTOR_TELEPHONE        63 non-null     int64
 19  PROGRAM_DIRECTOR_PHONE_EXTENSION  10 non-null     float64
 20  PROGRAM_TYPE                      63 non-null     object
 21  SERVICE_TYPE                      63 non-null     object
dtypes: float64(3), int64(5), object(14)
memory usage: 11.0+ KB

# 2. Cleaning data

In [14]:
# rename columns 
mcsilver_data         = mcsilver_data.rename(columns=lambda x:x.lower().replace(" ","_"))
omh_data              = omh_data.rename(columns=lambda x:x.lower().replace(" ","_"))
oasas_treatment_data  = oasas_treatment_data.rename(columns=lambda x:x.lower().replace(" ","_"))
oasas_prevention_data = oasas_prevention_data.rename(columns=lambda x:x.lower().replace(" ","_"))

# strip all column names 
mcsilver_data.columns         = mcsilver_data.columns.str.strip() 
omh_data.columns              = omh_data.columns.str.strip() 
oasas_treatment_data.columns  = oasas_treatment_data.columns.str.strip() 
oasas_prevention_data.columns = oasas_prevention_data.columns.str.strip()

# 3. Merging McSilver and OMH data

There are 1123/2156 rows in the McSilver dataset that have complete OMH program identification. 
We were able to match 877 addresses.

In [15]:
# subset columns to the ones we care about 
omh_subset = omh_data[["program_address_1", "program_address_2", 
                       "program_city", "program_state", "program_zip",
                       "agency_code", "facility_code", "program_code",  # omhProgramCode, omhFacilityCode, and OMH/OASAS Agency Code
                       "program_type"]]
omh_subset.head()

,program_address_1,program_address_2,program_city,program_state,program_zip,agency_code,facility_code,program_code,program_type
0,1003 Walnut Street,NaN,Elmira,NY,14901-1007,44810,7810,1,Partial Hospitalization
1,Agency Phone:Â (347)Â 978-1139,NaN,NaN,NY,NaN,30510,9233,1,SRO Community Residence
2,Agency Phone:Â (212)Â 274-8558,NaN,NaN,NY,NaN,18780,7062,6,SRO Community Residence
3,545 Eighth Avenue,Room 910,New York,NY,10018,18780,7062,10,Health Home Care Management
4,545 Eighth Avenue,Room 610,New York,NY,10018,18780,7062,11,Health Home Non-Medicaid Care Management

In [16]:
# drop all rows in the McSilver dataset that have any missing keys 
mcsilver_omh_subset = mcsilver_data.dropna(subset=["omhprogramcode", "omhfacilitycode", "omh/oasas_agency_code"], how="any")
print(mcsilver_omh_subset.shape)

(1123, 41)

In [17]:
# merge datasets 
mcsilver_omh_merged = mcsilver_omh_subset.merge(omh_subset, 
                                                left_on=["omhprogramcode", "omhfacilitycode", "omh/oasas_agency_code"], 
                                                right_on=["program_code", "facility_code", "agency_code"], 
                                                suffixes=(False, False),
                                                how="left")
print(mcsilver_omh_merged.shape) 
mcsilver_omh_merged["program_address_1"].isna().sum() # 246 missing addresses, 877 matches

# drop extra id variables 
mcsilver_omh_merged.drop(["program_code", "facility_code", "agency_code"], axis=1, inplace=True)

(1123, 50)

# 4. Merging McSilver and OASAS data

There are 321/2156 rows in the McSilver dataset that have complete OASAS program identification. 
We were able to match 234 addresses.

In [18]:
# stack two OASAS datasets 
oasas_data = pd.concat([oasas_treatment_data, oasas_prevention_data], axis=0)
print(oasas_data.shape)

(374, 34)

In [19]:
# subset columns to the ones we care about 
oasas_subset = oasas_data[["provider_number", "program_number", "service_type",
                           "program_street_address", "program_city", "program_county", "program_state", "program_zip_code"]]

# rename columns to match OMH data 
oasas_subset = oasas_subset.rename(columns={"program_street_address": "program_address_1", 
                                            "program_zip_code": "program_zip",
                                            "service_type": "program_type"})
oasas_subset.head()

,provider_number,program_number,program_type,program_address_1,program_city,program_county,program_state,program_zip
0,10160,227,Outpatient Clinic,830 Forest Ave,Bronx,Bronx,NY,10456
1,10160,53152,820 Rehab and Reintegration,830 Forest Ave,Bronx,Bronx,NY,10456
2,10160,53153,820 Rehab and Reintegration,830 Forest Ave,Bronx,Bronx,NY,10456
3,32412,52100,Outpatient Clinic,3584 Jerome Ave,Bronx,Bronx,NY,10467
4,1857,53297,820 Stabil Rehab Reintegration,1064 Franklin Ave,Bronx,Bronx,NY,10456

In [20]:
# drop all rows in the McSilver dataset that have any missing keys 
mcsilver_oasas_subset = mcsilver_data.dropna(subset=["oasasprogramcode", "omh/oasas_agency_code"], how="any")
print(mcsilver_oasas_subset.shape)

(321, 41)

In [21]:
# merge datasets 
mcsilver_oasas_merged = mcsilver_oasas_subset.merge(oasas_subset, 
                                                   left_on=["oasasprogramcode", "omh/oasas_agency_code"], 
                                                   right_on=["program_number", "provider_number"], 
                                                   suffixes=(False, False),
                                                   how="left")
print(mcsilver_oasas_merged.shape)  
mcsilver_oasas_merged["program_address_1"].isna().sum() # 93 missing addresses, 234 matches

# drop extra id variables 
mcsilver_oasas_merged.drop(["program_number", "provider_number"], axis=1, inplace=True)

(327, 49)

# 5. Other 

After doing the initial merge of OMH and OASAS data, we have 877+234 = 1111/2156 address matches. 
The complete OMH and OASAS data account for 1123+327 = 1450/2156 of the programs in the McSilver data.

In [22]:
# stack dataframes 
merged_data = pd.concat([mcsilver_omh_merged, mcsilver_oasas_merged], ignore_index=True, axis=0) 

# add flag for whether we were able to find the address
merged_data["matched_address"] = merged_data["program_address_1"].notna()
merged_data["matched_address"].sum()

# write file to Excel 
merged_data.to_excel("./out/mcsilver_omh_oasas_address_data.xlsx")

In [23]:
# get all other rows that we haven't looked at 
remaining_data = pd.merge(mcsilver_data, merged_data["internal_id"], how="left",indicator=True, on="internal_id")
remaining_data = remaining_data[(remaining_data._merge == "left_only")]

remaining_data.head()

# write to file to inspect 
remaining_data.to_excel("./out/remaining_data.xlsx")